// <auto-generated />
using System;
using ManufacturingSimulation.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManufacturingSimulation.Database.Migrations
{
    [DbContext(typeof(MesDbContext))]
    [Migration("20251105035121_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("component_id");

                    b.Property<string>("ComponentName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("component_name");

                    b.Property<string>("ComponentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("component_number");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSubcontracted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_subcontracted");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lead_time_days");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.Property<int?>("TypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type_id");

                    b.Property<double?>("UnitCost")
                        .HasColumnType("REAL")
                        .HasColumnName("unit_cost");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("ComponentId");

                    b.HasIndex("StudentId");

                    b.ToTable("components", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BufferCapacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buffer_capacity");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("ProcessingRate")
                        .HasColumnType("REAL")
                        .HasColumnName("processing_rate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("machines");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.MachineDistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("REAL")
                        .HasColumnName("distance_meters");

                    b.Property<int>("FromMachineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("from_machine_id");

                    b.Property<int>("ToMachineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("to_machine_id");

                    b.Property<double>("TravelTimeSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("travel_time_seconds");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("machine_distances");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.MachineLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("department");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("floor_number");

                    b.Property<int>("MachineId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("machine_id");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rotation");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<double>("XCoordinate")
                        .HasColumnType("REAL")
                        .HasColumnName("x_coordinate");

                    b.Property<double>("YCoordinate")
                        .HasColumnType("REAL")
                        .HasColumnName("y_coordinate");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.ToTable("machine_locations");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int?>("AssemblyTimeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("assembly_time_minutes");

                    b.Property<int?>("BomLevels")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bom_levels");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("product_number");

                    b.Property<double?>("SellingPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("selling_price");

                    b.Property<double?>("StandardCost")
                        .HasColumnType("REAL")
                        .HasColumnName("standard_cost");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.HasKey("ProductId");

                    b.HasIndex("StudentId");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.ProductionOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("due_date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("order_number");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("release_date");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.HasKey("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StudentId");

                    b.ToTable("production_orders", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.Routing", b =>
                {
                    b.Property<int>("RoutingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("routing_id");

                    b.Property<int?>("BatchSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batch_size");

                    b.Property<string>("CycleTimeDistribution")
                        .HasColumnType("TEXT")
                        .HasColumnName("cycle_time_distribution");

                    b.Property<double?>("CycleTimeMinutes")
                        .HasColumnType("REAL")
                        .HasColumnName("cycle_time_minutes");

                    b.Property<double?>("CycleTimeStdDev")
                        .HasColumnType("REAL")
                        .HasColumnName("cycle_time_std_dev");

                    b.Property<bool?>("IsBufferOnly")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_buffer_only");

                    b.Property<double?>("LaborHours")
                        .HasColumnType("REAL")
                        .HasColumnName("labor_hours");

                    b.Property<string>("OperationName")
                        .HasColumnType("TEXT")
                        .HasColumnName("operation_name");

                    b.Property<int>("OperationSeq")
                        .HasColumnType("INTEGER")
                        .HasColumnName("operation_seq");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<string>("SetupTimeDistribution")
                        .HasColumnType("TEXT")
                        .HasColumnName("setup_time_distribution");

                    b.Property<double?>("SetupTimeMean")
                        .HasColumnType("REAL")
                        .HasColumnName("setup_time_mean");

                    b.Property<int?>("SetupTimeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("setup_time_minutes");

                    b.Property<double?>("SetupTimeStdDev")
                        .HasColumnType("REAL")
                        .HasColumnName("setup_time_std_dev");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.Property<int>("WorkCenterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_center_id");

                    b.HasKey("RoutingId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StudentId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("routings", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.DbSimEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("details");

                    b.Property<double>("EventTime")
                        .HasColumnType("REAL")
                        .HasColumnName("event_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("event_type");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("machine_name");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("order_number");

                    b.Property<string>("PartId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("part_id");

                    b.Property<int>("QueueSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("queue_size");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.HasKey("EventId");

                    b.HasIndex("RunId");

                    b.ToTable("simulation_events");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationOrderPrediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completed");

                    b.Property<int>("PartsCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parts_completed");

                    b.Property<double?>("PredictedCompletionTime")
                        .HasColumnType("REAL")
                        .HasColumnName("predicted_completion_time");

                    b.Property<double?>("PredictedFlowTimeHours")
                        .HasColumnType("REAL")
                        .HasColumnName("predicted_flow_time_hours");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("production_order_id");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("RunId");

                    b.ToTable("simulation_order_predictions", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("result_id");

                    b.Property<double>("AvgFlowTimeHours")
                        .HasColumnType("REAL")
                        .HasColumnName("avg_flow_time_hours");

                    b.Property<double>("AvgWip")
                        .HasColumnType("REAL")
                        .HasColumnName("avg_wip");

                    b.Property<double>("OverallUtilizationPercent")
                        .HasColumnType("REAL")
                        .HasColumnName("overall_utilization_percent");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.Property<double>("SimulatedTimeHours")
                        .HasColumnType("REAL")
                        .HasColumnName("simulated_time_hours");

                    b.Property<double>("Throughput")
                        .HasColumnType("REAL")
                        .HasColumnName("throughput");

                    b.Property<int>("TotalPartsArrived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_parts_arrived");

                    b.Property<int>("TotalPartsCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_parts_completed");

                    b.HasKey("ResultId");

                    b.HasIndex("RunId")
                        .IsUnique();

                    b.ToTable("simulation_results", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationRun", b =>
                {
                    b.Property<int>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("config_json");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("run_date");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scenario_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.HasKey("RunId");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("StudentId");

                    b.ToTable("simulation_runs", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationScenario", b =>
                {
                    b.Property<int>("ScenarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("scenario_id");

                    b.Property<DateTime?>("BaseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("random_seed");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scenario_name");

                    b.Property<double>("SimulationDurationHours")
                        .HasColumnType("REAL")
                        .HasColumnName("simulation_duration_hours");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.HasKey("ScenarioId");

                    b.HasIndex("StudentId");

                    b.ToTable("simulation_scenarios", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationScenarioOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("production_order_id");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scenario_id");

                    b.HasKey("Id");

                    b.ToTable("simulation_scenario_orders");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationWorkCenterResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("AvgQueueSize")
                        .HasColumnType("REAL")
                        .HasColumnName("avg_queue_size");

                    b.Property<double>("AvgWaitTimeHours")
                        .HasColumnType("REAL")
                        .HasColumnName("avg_wait_time_hours");

                    b.Property<bool>("IsBottleneck")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_bottleneck");

                    b.Property<int>("MaxQueueSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_queue_size");

                    b.Property<int>("PartsProcessed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parts_processed");

                    b.Property<int>("RunId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_id");

                    b.Property<double>("UtilizationPercent")
                        .HasColumnType("REAL")
                        .HasColumnName("utilization_percent");

                    b.Property<int>("WorkCenterId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_center_id");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.HasIndex("WorkCenterId");

                    b.ToTable("simulation_work_center_results", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_date");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("StudentId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.WorkCenter", b =>
                {
                    b.Property<int>("WorkCenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("work_center_id");

                    b.Property<double>("AvailabilityPercent")
                        .HasColumnType("REAL")
                        .HasColumnName("availability_percent");

                    b.Property<int?>("BufferCapacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buffer_capacity");

                    b.Property<double?>("CapacityUnitsPerHour")
                        .HasColumnType("REAL")
                        .HasColumnName("capacity_units_per_hour");

                    b.Property<int?>("DepreciationYears")
                        .HasColumnType("INTEGER")
                        .HasColumnName("depreciation_years");

                    b.Property<double?>("InvestmentCost")
                        .HasColumnType("REAL")
                        .HasColumnName("investment_cost");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBottleneck")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_bottleneck");

                    b.Property<double?>("OperatingCostPerHour")
                        .HasColumnType("REAL")
                        .HasColumnName("operating_cost_per_hour");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<bool>("RequiresOperator")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requires_operator");

                    b.Property<int>("SetupTimeMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("setup_time_minutes");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_date");

                    b.Property<int?>("WcTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("wc_type_id");

                    b.Property<string>("WorkCenterCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("work_center_code");

                    b.Property<string>("WorkCenterName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("work_center_name");

                    b.HasKey("WorkCenterId");

                    b.HasIndex("StudentId");

                    b.ToTable("work_centers", (string)null);
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.Component", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.MachineLocation", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.Product", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.ProductionOrder", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManufacturingSimulation.Database.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.Routing", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.Product", "Product")
                        .WithMany("Routings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManufacturingSimulation.Database.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManufacturingSimulation.Database.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Student");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.DbSimEvent", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.SimulationRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationOrderPrediction", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManufacturingSimulation.Database.Models.SimulationRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationResult", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.SimulationRun", "Run")
                        .WithOne("Result")
                        .HasForeignKey("ManufacturingSimulation.Database.Models.SimulationResult", "RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationRun", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.SimulationScenario", "Scenario")
                        .WithMany("Runs")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManufacturingSimulation.Database.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationScenario", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationWorkCenterResult", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.SimulationRun", "Run")
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManufacturingSimulation.Database.Models.WorkCenter", "WorkCenter")
                        .WithMany()
                        .HasForeignKey("WorkCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");

                    b.Navigation("WorkCenter");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.WorkCenter", b =>
                {
                    b.HasOne("ManufacturingSimulation.Database.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.Product", b =>
                {
                    b.Navigation("Routings");
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationRun", b =>
                {
                    b.Navigation("Result")
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingSimulation.Database.Models.SimulationScenario", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
